// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.InteropServices

[<assembly: AssemblyTitleAttribute("FPrimitive")>]
[<assembly: AssemblyDescriptionAttribute(".NET project to help developers build a correct and more secure domain model.")>]
[<assembly: GuidAttribute("771121cs-r6e3-38c5-98b1-6cec4c286948")>]
[<assembly: AssemblyProductAttribute("FPrimitive")>]
[<assembly: AssemblyVersionAttribute("3.2.1")>]
[<assembly: AssemblyFileVersionAttribute("3.2.1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FPrimitive"
    let [<Literal>] AssemblyDescription = ".NET project to help developers build a correct and more secure domain model."
    let [<Literal>] Guid = "771121cs-r6e3-38c5-98b1-6cec4c286948"
    let [<Literal>] AssemblyProduct = "FPrimitive"
    let [<Literal>] AssemblyVersion = "3.2.1"
    let [<Literal>] AssemblyFileVersion = "3.2.1"
